language: android

android:
  components:
    - build-tools-28.0.3
    - android-29
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    
jdk:
  - openjdk8

dist: trusty

branches:
  only:
    - master

script:
  - ./gradlew assembleDebug testDebugUnitTest
