name: CI Android

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java_version: [ 17 ]
    steps:
      - uses: actions/checkout@v5
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: ${{ matrix.java_version }}
      - uses: gradle/wrapper-validation-action@v3.5.0
      - name: Build with Gradle
        run: ./gradlew assembleDebug lint testDebugUnitTest
      - name: Archive Lint report
        uses: actions/upload-artifact@v4
        with:
          name: Lint-report
          path: app/build/reports/lint-results.html