name: CI Android

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java_version: [ 17 ]
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0
          fetch-tags: true
      - name: set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: "adopt"
          java-version: ${{ matrix.java_version }}
      - uses: gradle/actions/wrapper-validation@v5
      - name: Build with Gradle
        run: ./gradlew assembleDebug lint
      - name: Archive Lint report
        uses: actions/upload-artifact@v5
        with:
          name: Lint-report
          path: app/build/reports/lint-results.html